const data = [
    "JavaScript",
    "Python",
    "Java",
    "C++",
    "React",
    "Node.js",
    "Angular",
    "Vue.js",
    "PHP",
    "HTML",
    "CSS",
    "Swift",
    "Kotlin",
    "Objective-C",
    "SQL",
    "Git",
    "GitHub",
    "Visual Studio Code",
    "Eclipse",
    "IntelliJ IDEA",
    "Android Studio",
    "Xcode",
    "Atom",
    "Sublime Text",
    "Emacs",
    "NetBeans",
    "PHPStorm",
    "WebStorm",
    "PyCharm",
    "RubyMine",
    "Code::Blocks",
    "Dev-C++",
    "Visual Studio",
    "CodeLite",
    "Qt Creator",
    "Notepad++",
    "Brackets",
    "BlueJ",
    "CodePen",
    "JSFiddle",
    "CodeSandbox",
    "Repl.it",
    "Stack Overflow",
    "GitHub Pages",
    "Heroku",
    "Amazon Web Services",
    "Google Cloud Platform",
    "Microsoft Azure",
    "Docker",
    "Kubernetes",
    "Apache",
    "Nginx",
    "MySQL",
    "MongoDB",
    "PostgreSQL",
    "SQLite",
    "Redis",
    "Oracle",
    "Microsoft SQL Server",
    "IBM DB2",
    "Amazon RDS",
    "Google Cloud SQL",
    "Microsoft Azure SQL Database",
    "Apache Cassandra",
    "Apache Hadoop",
    "Apache Spark",
    "Apache Kafka",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "NumPy",
    "Pandas",
    "Matplotlib",
    "Seaborn",
    "Bokeh",
    "D3.js",
    "Plotly",
    "Tableau",
    "Power BI",
    "Google Analytics",
    "Adobe Analytics",
    "Heap Analytics",
    "Amplitude",
    "Mixpanel",
    "Segment",
    "Google Tag Manager",
    "Adobe Tag Manager",
    "Hotjar",
    "Crazy Egg",
    "Optimizely",
    "VWO",
    "Google Optimize",
    "AB Tasty",
    "Unbounce",
    "Instapage",
    "Leadpages",
    "Mailchimp",
    "SendGrid",
    "Constant Contact",
    "HubSpot",
    "Marketo",
    "Pardot",
    "Intercom",
    "Zendesk",
    "Drift",
    "LiveChat",
    "Olark",
    "Slack",
    "Microsoft Teams",
    "Zoom",
    "Skype",
    "Google Meet",
    "Webex",
    "Asana",
    "Trello",
    "Jira",
    "Monday.com",
    "Notion",
    "Google Drive",
    "Dropbox",
    "OneDrive",
    "Box"
  ];